name: Run Python 2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Take value from Github
        run: |
          echo "Name:" ${{secrets.USER_NAME}} | sed 's/./& /g'
          echo "apt-get update -y"
          echo "apt-get Upgrade -y"
          echo "apt install -y net-tools -y"