name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add your build steps here

  deploy1:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  deploy2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add your deployment steps here
  deploy3:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add your deployment steps here

  analyze:
    runs-on: ubuntu-latest
    needs: [deploy1, deploy2, deploy3]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add your analysis steps here
